version: '3'

services:
    app:
        build: dkron/dkron:v0.10.2
        volumes:
          - './dkron-agent.json:/etc/dkron/dkron.json'
        command: "agent"
        tty: true
        networks:
          - dkron
          - app
          - redis
        expose:
            - 8946

networks:
    dkron:
        external:
          name: dkron_dkron
    app:
        driver: bridge
    redis:
        external:
          name: redis_redis
